### ISSUE TITLE
Access to "error", "status" and "meta" fields in responses

### ISSUE THREAD

**Issue by kakwa** [IceflowRE/go-wargaming#2]
Having access to the "error", "status" and "meta" would be really nice.

In particular, the "meta" field can contain pagination information (ex: number of items, number of pages) which are extremely helpful when iterating through paginated lists.

Response payload examples:

* error:
```json
{
    "status": "error",
    "error": {
        "field": "ship_id",
        "message": "INVALID_SHIP_ID",
        "code": 407,
        "value": "3315513040a"
    }
}
```

* status + meta:
```json
{
    "status": "ok",
    "meta": {
      "count": 100,
      "page_total": 7,
      "total": 608,
      "limit": 100,
      "page": 1
    },
    "data": {
        "3315513040": {
            "ship_id": 3315513040,
            "name": "[Zaō]"
        }
    }
}

**Comment by IceflowRE** [comment]
I will take a look how to achieve that.

**Comment by IceflowRE** [comment]
## Error
You already get access to the whole error field
```go
_, err := client.Wot.AccountList(context.Background(), RealmEu, "Licht", nil)
var respErr *ResponseError
if errors.As(err, &respErr) {
	if respErr.Code == 504 {
		fmt.Println("Method seems to be deprecated.")
	}
}
```
[`wargaming.ResponseError`](https://pkg.go.dev/github.com/IceflowRE/go-wargaming/v3/wargaming#ResponseError)

## Status
Is the returned error nil, status was `ok`. If the returned error  was of type `ResponseError` it was `error`.

## Meta

You are right, there is no easy way, to get that field currently, will work on that!

**Comment by IceflowRE** [comment]
@kakwa 
You should be now able to get the meta return field. At least for some specific endpoints, more are following soon. I added `Wows.EncyclopediaShips` especially as you are using it.
You can get the version with the meta return field with 
```
go get github.com/IceflowRE/go-wargaming/v3@5fdc7300c5fdd7acde9d976b0d5aafcf48340af3
```

**Comment by kakwa** [comment]
thanks, I will take a look.

**Comment by IceflowRE** [comment]
Finished with 0015da771f7ceb719ce45c358b19ea97c2faba5c.
Introduced a `GenericMeta` struct which covers all known possible meta values.
