### ISSUE TITLE
[generator] Document how to use the generator in a fork

### ISSUE THREAD

**Issue by kakwa** [IceflowRE/go-wargaming#6]
When fixing the generator (patchs.go fixes), a contributor needs to build the local patched version.

However `go build -o generator github.com/IceflowRE/go-wargaming/v4/tools/generator` (like instructed in the README) will build the unpatched version from the upstream repository, not the local checkout.

It's possible to build the generator locally (`go build -o generator tools/_generator/main.go`, but it has other side effects, mainly messing-up the imports:

```diff
 import (
-       "github.com/IceflowRE/go-wargaming/v4/wargaming/wgnTime"
+       "/wargaming/wgnTime"
 )
```

Put also adding `//` spacing comment lines:

```diff
 // realm:
-//     Valid realms: RealmAsia, RealmEu, RealmNa
+//
+//     Valid realms: RealmAsia, RealmEu, RealmNa
+//
 // search:
-//     Player name search string. Parameter "type" defines minimum length and type of search. Using the exact search type, you can enter several names, separated with commas. Maximum length: 24.
+//
+//     Player name search string. Parameter "type" defines minimum length and type of search. Using the exact search type, you can enter several names, separated with commas. Maximum length: 24.
```

My go version:

```shell
> go version
go version go1.19.8 linux/amd64
```

**Comment by IceflowRE** [comment]
Woops. Will take a look.

**Comment by IceflowRE** [comment]
I could not reproduce the local build failure.
If i do
```
go build -o generator github.com/IceflowRE/go-wargaming/v4/tools/_generator
```
it will build from the local version.
Probably you had the newest version and did
```
go build -o generator github.com/IceflowRE/go-wargaming/v4/tools/generator
```
Note the missing underscore. I added the underscore, that the tools wont be delivered when doing `go get`. This might have been the issue here.
Will update the readme.

**Comment by IceflowRE** [comment]
The generator generation should be correct now. The formatting is continued here #8 .
If i am wrong please reopen, with additional information.
